/**
 * The preset profile images an agent or team can pick instead of uploading one.
 *
 * They are static SVGs in `web/public/avatars/` (regenerated by
 * `web/scripts/generate-preset-avatars.mjs`), so a preset's `profileImageUrl`
 * is just its path and every surface that renders a profile image shows it
 * with no special case. The backend accepts exactly this list
 * (`backend/relay/core/preset_avatars.py`); tests on both sides check it
 * against the files on disk.
 */

export type PresetAvatarKind = "agents" | "teams";

function presetUrls(kind: PresetAvatarKind, style: string, count: number): readonly string[] {
  return Array.from(
    { length: count },
    (_, index) => `/avatars/${kind}/${style}-${String(index + 1).padStart(2, "0")}.svg`,
  );
}

export const PRESET_AVATARS: Readonly<Record<PresetAvatarKind, readonly string[]>> = {
  agents: presetUrls("agents", "bottts", 16),
  teams: presetUrls("teams", "shape-grid", 12),
};

export function isPresetAvatarUrl(kind: PresetAvatarKind, url: string | null | undefined): boolean {
  return typeof url === "string" && PRESET_AVATARS[kind].includes(url);
}

/** A preset for a new record, so nothing is created wearing the blank default. */
export function randomPresetAvatar(kind: PresetAvatarKind, random: () => number = Math.random): string {
  const presets = PRESET_AVATARS[kind];
  const index = Math.min(presets.length - 1, Math.floor(random() * presets.length));
  return presets[index]!;
}
